package com.amituofo.common.type;

public enum AppProtocol {
	HTTP                  ,
//	DNS                   ,
	FTP                   ,
	SMTP                  ,
	POP3                  ,
	IMAP                  ,
	Telnet                ,
	SSH                   ,
	SNMP                  ,
//	TLS/SSL               ,
	DHCP                  ,
	SMB                   ,
//	AFP                   ,
//	NNTP                  ,
//	IRC                   ,
//	XMPP                  ,
//	BitTorrent            ,
//	RTP                   ,
//	RTSP                  ,
//	SIP                   ,
//	NTP                   ,
//	LDAP                  ,
//	DHCPv6                ,
//	RADIUS                ,
	TFTP                  ,
//	Gopher                ,
//	Finger                ,
//	DNSSEC                ,
//	Kerberos              ,
//	ISAKMP                ,
//	IKE                   ,
//	SMB2                  ,
//	AFP3                  ,
//	LPD                   ,
//	IPP                   ,
//	SSDP                  ,
//	UPnP                  ,
//	Bonjour               ,
//	LDAPs                 ,
//	LDAPS                 ,
//	SNMPv3                ,
//	PPTP                  ,
//	L2TP                  ,
//	OpenVPN               ,
	RDP                   ,
	VNC                   ,
	MQTT                  ,
//	CoAP                  ,
//	XMPP                  ,
	AMQP                  ,
	SMTPS                 ,
	IMAPS                 ,
	POP3S                 ,
//	NNTPS                 ,
	HTTPS                 ,
	SSH2                  ,
	SFTP                  ,
//	SCP                   ,
//	IKEv2                 ,
//	QUIC                  ,
//	DNS-over-HTTPS        ,
//	DNS-over-TLS          ,
//	SSTP                  ,
//	BitTorrent Sync       ,
	WebDAV                ,
//	ACAP                  ,
//	BGP                   ,
//	IRCs                  ,
//	TELNETS               ,
//	RLOGIN                ,
//	RSH                   ,
//	SNMPv2                ,
//	SNMP-Traps            ,
//	SIPs                  ,
//	LDAPv3                ,
//	LDAPv2                ,
//	IRCd                  ,
	CIFS              ,
	NFS                   ,
//	SMTP AUTH             ,
//	S/MIME                ,
//	NSAPI                 ,
//	PAP                   ,
//	CHAP                  ,
//	MS-CHAP               ,
//	MS-CHAPv2             ,
//	MSRPC                 ,
//	RDP over SSL          ,
//	SPX                   ,
//	IPX/SPX               ,
//	Novell NetWare        ,
//	Banyan Vines          ,
//	DECnet                ,
//	AppleTalk             ,
//	X.25                  ,
//	Frame Relay           ,
//	ISDN                  ,
//	ATM；
}
